# Reverse Linux VNC for GitHub Actions
# This YAML establishes the "build" workflow where we will execute all required scripts
# During the process, it should get stuck at the last step where it creates a new tunnel on ngrok.

name: Ubuntu
on: [push]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparing environment...
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: ./scripts/configure.sh
    - name: Starting VNC Server...
      run: cd $HOME && vncserver :1 -geometry 800x600 -depth 24 -rfbport 7582
    - name: Creating tunnel with ngrok...
      run: ./ngrok tcp 7582