name: test
on: [push]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: quick commands 1
      run: pwd
    - name: dir listing
      run: ls -la
    - name: env variables
      run: env
    - name: Script execution
      run: bash configure.sh